name: ShopSphere CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

- name: Read Secret
        env:
          MY_SECRET: ${{ secrets.MY_FIRST_SECRET }}
        run: echo "Secret Loaded Successfully"

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore ShopSphere.sln

      - name: Build Solution
        run: dotnet build ShopSphere.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test ShopSphere.sln --configuration Release --no-build

      - name: Publish Application
        run: dotnet publish ShopSphere.Api/ShopSphere.API.csproj --configuration Release --no-build --output publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShopSphere-Publish
          path: publish